version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: compras_modular_db
    environment:
      - POSTGRES_USER=compras_user
      - POSTGRES_PASSWORD=compras_password
      - POSTGRES_DB=compras_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: compras_modular_backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db # Sobrescreve o DB_HOST do .env para usar o container do banco
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: compras_modular_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
